[image_processing]
path_to_training_data = "images/training"
path_to_test_data = "images/test"
path_to_agents_dir= "images/agents"
image_width = 33
image_height = 25
retina_size = 5
retina_highlight_alpha = 100

[neural_network]
neurons_per_network = 6
number_of_network_updates = 20
movement_scale = 4.0

[neural_network.weight_bounds]
neuron_lower = -10.0
neuron_upper = 10.0
retina_lower = -1.0
retina_upper = 1.0

[genetic_algorithm]
seed = 554
population_size = 100
max_generations = 1000
tournament_size = 5

[genetic_algorithm.mutation_rates]
variance = 0.2
mean = 0.0
delete_neuron = 0.1
delete_weights = 0.1
delete_bias = 0.1
delete_self_activation = 0.1
mutate_neuron = 0.2
mutate_weights = 0.2
mutate_bias = 0.1
mutate_self_activation = 0.1